from DRCF import *
## --- Variabelen ---
Steps = 0
firstRun = True
##pneumatic cilinder list
set_digital_output(1, OFF) #Second arm cilinder  #off extended
set_digital_output(2, ON) #robot arm gripper #ON is open to suck 
set_digital_output(3, OFF) #Towel blower off towel #off is off
set_digital_output(4, ON) #Second arm gripper #off is closed
set_digital_output(5, ON) #Venturi  #on is off
set_digital_output(6, ON) ##Second arm cilinder #NO

##Variables used in the loop
global variables
TowelVisible = False
FirstCornerVisible = False
GrabbedFirstCorner = False
GrabbedSecondCorner = False
CheckForCorner = False

XfirstCorner = 0.0
YfirstCorner = 0.0
ZfirstCorner = 30.0
ZcornerHeight = 25.0
ZcornerPickupHeigt = 60.0
AngleA = 0
AngleB = 180
AngleC = 0.0
vel150 = 150
acc400 = 400



##Fixed coordinates #in order of steps
##step 1
startpos = posx([572.52, -542.23, 219.95, AngleA, AngleB, 180])
##step 8
endOTabelCoords = posx([1106.4,-63.7,430.60,173.83,-136.27, -41.38])

endOTabelCoords = posx([1106.4,-200.7,430.60,173.83,-136.27, -41.38])

##step 9

endOTabelCoordsLoweredTest2anglecilinderfurthertotable = [1066.22, 5 ,55.41,168.70,162.28,-143.50]
Cylinder2coords = [1084.7, 11.07, 54.35, 8.34, -164.36, 51.22]

##step 10

RobotUpThroughCylinder = posx([999.13, 10.79,460,38.47,167.50, 89.73])

LinearAxisUpTEST = posx([999.13,-34.79,450,38.47,167.50, 89.73])

##step 11
Straight2gripperholdTEST2 = [1027.29, -240, 69.46, 58.18, -178.21, 78.94]
#step 12
AfterThirdGripper = posx(1027.54, -220.64, 120.24, 58.44, -178.21, 78.94)


sock = None

## --- Socket receive and processing data ---
def ReadSocketData(msg):
    global TowelVisible, FirstCornerVisible, SecondCornerVisible
    global XfirstCorner, YfirstCorner, XsecondCorner, YsecondCorne, ZfirstCorner
    global XtableCorner, YtableCorner, XcoordsArmLinearAxis, YcoordsArmLinearAxis
    global XcoordsEndOfTable, YcoordsEndOfTable
    global AngleA, AngleB, AngleC

   
    if msg != None and msg != "":
        parts = msg.split(";")
        for pair in parts:
            if pair != "":
                kv = pair.split("=")
                if len(kv) == 2:
                    key = kv[0]
                    value = kv[1]
                    if key == "TowelVisible":
                        TowelVisible = (value == "1")
                    elif key == "FirstCornerVisible":
                        FirstCornerVisible = (value == "1")
                    elif key == "XfirstCorner":
                        XfirstCorner = float(value)
                    elif key == "YfirstCorner":
                        YfirstCorner = float(value)
                    elif key == "Z":
                        ZfirstCorner = float(value)
                    elif key == "C":
                        AngleC = float(value)

def Main():
    global Steps, ConveyorBelt, TowelVisible, FirstCornerVisible, SecondCornerVisible, firstRun
    global GrabbedFirstCorner, GrabbedSecondCorner, TakeLatestPicture, CheckForCorner
    global XfirstCorner, YfirstCorner, XsecondCorner, YsecondCorner
    global XtableCorner, YtableCorner, XcoordsArmLinearAxis, YcoordsArmLinearAxis, ZfirstCorner
    global XcoordsEndOfTable, YcoordsEndOfTable
    global T1_start, T1_running, T2_start, T2_running
    global AngleA, AngleB, AngleC
    

    while True:
        ## Step 0 nothing move on to step 1
        if Steps == 0:
            set_digital_output(3, OFF) #Towel blower off towel #off is off
            set_digital_output(1, OFF) #Second arm cilinder  #off extended
            sock = client_socket_open('192.168.137.10', 5000)
            msgToLaptop = "CheckForCorner=1"
            client_socket_write(sock,  msgToLaptop.encode())
            Steps = 1
        ##Step 1 init and move back to start position
        elif Steps == 1:
            TowelVisible = False
            FirstCornerVisible = False
            GrabbedFirstCorner = False
            GrabbedSecondCorner = False
            TakeLatestPicture = False
            CheckForCorner = False

            XfirstCorner = 0.0; YfirstCorner = 0.0
            ZfirstCorner = 24.0
            AngleFirstCorner = 0.0
            set_digital_output(2, ON) #robot arm gripper #ON is open to suck 
            set_digital_output(4, ON) #Second arm gripper #off is closed
            set_digital_output(5, ON) #Venturi  #on is off
            set_digital_output(6, ON) ##Second arm cilinder #NO
            set_digital_output(7, OFF) ##Second arm cilinder #NO
            

            movejx(startpos,vel150,acc400,sol=2)
            Steps = 2
            
        ##step 2 give signal for detection to laptop
        elif Steps == 2: ## If corner is found go to pickup step else go to blow towel away step
            if firstRun:
                firstRun = False
            else:
                set_digital_output(3, ON, 2, OFF) #towel blower away
                set_digital_output(1, ON, 1.5, OFF) #Second arm cilinder  #off extended
            CheckForCorner = True
            resp, recv = client_socket_read(sock)
            client_socket_close(sock)
            msg = recv.decode()
            ReadSocketData(msg) ##read the respons from the laptop 
            #wait(0.1)
            if TowelVisible:
                Steps = 3
                
        ##step 3 check if firstcorner is visible 
        elif Steps == 3: 
            if FirstCornerVisible:
                Steps = 4
                
            else: 
                Steps = 104
                
        ##step 4 move to slightly higher than the corner coords
        elif Steps == 4: 

            PickupCoordsAbove = posx([XfirstCorner,YfirstCorner,55.2,AngleA,AngleB,AngleC])
            movejx(PickupCoordsAbove,vel150,acc400,sol=2)
            Steps = 5
            
        ##step 5 go to the corner and same height
        elif Steps == 5: ##Move to edge of table
            set_digital_output(1, OFF) ##Second and third arm cilinder #NO
            set_digital_output(3, OFF) ##Second and third arm cilinder #NO
            PickupCoords = posx([XfirstCorner,YfirstCorner,ZfirstCorner,AngleA,AngleB,AngleC])
            movejx(PickupCoords,vel=100,acc=250,sol=2)
            Steps = 6

        ##step 6 start sucking on towel and slightly raise it
        elif Steps == 6:
            set_digital_output(2, ON)
            set_digital_output(5, OFF) #Venturi
            wait(0.1)
            PickupCoordsSuckedAndRaised = posx([XfirstCorner,YfirstCorner,42.2,AngleA,AngleB,AngleC])
            movejx(PickupCoordsSuckedAndRaised,vel=75,acc=300,sol=2) 
            Steps = 7
          
        ##step 7 clamp the towel and move up 
        elif Steps == 7:
            set_digital_output(2, OFF) #robot arm gripper #ON is open to suck 
            set_digital_output(5, ON) #Venturi
             ##set the blower on 
       
            PickupCoordsClampedAndHigh = posx([XfirstCorner,YfirstCorner,100.2,AngleA,AngleB,AngleC])
            #movejx(PickupCoordsClampedAndHigh,vel=140,acc=350,sol=2) 
            set_digital_output(4, ON) ##Second arm cilinder #NO
            set_digital_output(6, ON) ##Second arm cilinder #NO

            Steps = 8
            
        ##Step 8 move to the edge of the table
        elif Steps == 8:
            movejx(endOTabelCoords,vel = 75,acc = 175,sol=2, radius = 25)
            ##set the blower off 
            wait(0.1)
            Steps = 9

        ##Step 9 move to the 2nd cilinder and clamp it
        ##########3cahnge
        elif Steps == 9:
            #Cylinder2coords = [1084.7, 11.07, 54.35, 8.34, -164.36, 51.22]
            Cylinder2coords = [1079.7, 11.07, 59.35, 8.34, -164.36, 51.22]
            #Cylinder2coordsbefore =  [1079.7, 5.07, 59.35, 8.34, -164.36, 51.22]
            
            endOTabelCoordsLoweredTest2anglecilinderfurthertotable = [1066.22, 0 ,55.41,168.70,162.28,-143.50]
            for _ in range(18):
                Cylinder2coords[1] += 5     # alleen Y aanpassen
                movejx(posx(Cylinder2coords), vel=150, acc=350, sol=2, radius=1.5)
            wait(0.2)
            noTowel = False
            PhotoCellSensor = get_digital_input(2)
            if(PhotoCellSensor):
                    noTowel = False
            else:
                    noTowel = True
            set_digital_output(4, OFF) ##Second arm gripper #ON is open
           
            if (noTowel):
                Steps = 209
            else:
                Steps = 10

        ##step 10 move through the 2nd gripper up 
        elif Steps == 10: 
            movejx(RobotUpThroughCylinder,vel=50,acc=95,sol = 2)
            wait(0.1)
            
            Steps = 11
        
        ##step 11 feed the 3rd cylinder and gripper
        ##########3cahnge
        elif Steps == 11:
            Straight2gripperholdTEST2 = [1068.51, -239, 55.46, 179.18, 166.21, -141.94]
            for _ in range(17):
                Straight2gripperholdTEST2[1] -= 5     # alleen Y aanpassen
                movejx(posx(Straight2gripperholdTEST2), vel=150, acc=380, sol=2, radius=1.5)

            set_digital_output(6, OFF) ##Second arm cilinder #NO
            wait(0.1)
            set_digital_output(2, ON)  ##robot arm gripper #ON is open to suck 
            wait(0.1)
            Steps = 12
            
        ##step 12 move slightly away from the 3rd gripper
        elif Steps == 12:
            movejx(AfterThirdGripper,vel150,acc400,sol=2, radius = 25)
            Steps = 13

        ##step 13 move both cylinders back to lay towel flat
        elif Steps == 13:
            set_digital_output(4, OFF, 0.97, ON) ##Second arm cilinder #NO
            set_digital_output(6, OFF, 0.94, ON) ##Second arm cilinder #NO
            set_digital_output(1, ON) ##Second and third arm cilinder #NO
            Steps = 14
            
        ##step 14 move both cylinders back to lay towel flat
        elif Steps == 14:
            sock = client_socket_open('192.168.137.10', 5000)
            msgToLaptop = "CheckForCorner=1"
            client_socket_write(sock,  msgToLaptop.encode())
            movejx(startpos,vel = 140 ,acc = 370,sol=2, radius = 25)
            Steps = 15
            
        ##step 15 let go of both cylinder grippers
        elif Steps == 15:
            set_digital_output(3, ON) ##Second and third arm cilinder #NO
            
            Steps = 1        
       
        ##step 104 if no corner then blow towel away
        elif Steps == 104: 
             set_digital_output(7, ON)  ##robot arm gripper #ON is open to suck
             wait(2)
             set_digital_output(7, OFF)  ##robot arm gripper #ON is open to suck
             Steps = 105
        
        ##step 105 go back to the start
        elif Steps == 105:
            Steps = 0
            set_digital_output(2, ON)  ##robot arm gripper #ON is open to suck 
       ##step 209 if no towel is detected at the photocell sensor     
        elif Steps == 209:
            set_digital_output(2, ON)  ##robot arm gripper #ON is open to suck 
            set_digital_output(4, ON)  ##robot arm gripper #ON is open to suck 
            set_digital_output(3, ON)  ##robot arm gripper #ON is open to suck
            set_digital_output(7, ON)  ##robot arm gripper #ON is open to suck
            wait(3)
            set_digital_output(3, OFF)  ##robot arm gripper #ON is open to suck
            set_digital_output(7, OFF)  ##robot arm gripper #ON is open to suck

            Steps = 0

            
        ##default step if it has wrong value go back to start
        else:
            Steps = 0

Main()
